version: '3.7'

services:
  app:
    build: .
    container_name: exchange_viewer_app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
  postgres:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5436:5432
    env_file:
      - .env
  redis:
    image: redis
  celery:
    build: .
    command: celery -A exchange_viewer_app.celery worker -l info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  celery-beat:
    build: .
    env_file:
      - .env
    command: celery -A exchange_viewer_app.celery beat -l info
    volumes:
      - .:/code
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

volumes:
  postgres_data:
